### PR TITLE
Styling branch

### PR DESCRIPTION
**Pull request by loganfmorro**
finished game js styling and added png logos

### CODE REVIEW

**Review by dmcc789 — COMMENTED** [review]
reviewed mainly css related changes.  resolved a conflict on canvas erase button to maintain style adjustments as well as onclick functionality.

**Comment by dmcc789** [comment]
I am trying to review approve and merge this branch to main...

**Review by clairevita — APPROVED** [review]
resolved

**Review by dmcc789 — COMMENTED** [review]
this looks good

**Pull request merged**
